// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: proto.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChitChat_GetChits_FullMethodName  = "/ChitChat/GetChits"
	ChitChat_SendChits_FullMethodName = "/ChitChat/SendChits"
	ChitChat_JoinChit_FullMethodName  = "/ChitChat/JoinChit"
	ChitChat_LeaveChit_FullMethodName = "/ChitChat/leaveChit"
)

// ChitChatClient is the client API for ChitChat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChitChatClient interface {
	GetChits(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chits], error)
	SendChits(ctx context.Context, in *Chit, opts ...grpc.CallOption) (*Chits, error)
	JoinChit(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*Join, error)
	LeaveChit(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Leave, error)
}

type chitChatClient struct {
	cc grpc.ClientConnInterface
}

func NewChitChatClient(cc grpc.ClientConnInterface) ChitChatClient {
	return &chitChatClient{cc}
}

func (c *chitChatClient) GetChits(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Chits], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChitChat_ServiceDesc.Streams[0], ChitChat_GetChits_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, Chits]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChitChat_GetChitsClient = grpc.ServerStreamingClient[Chits]

func (c *chitChatClient) SendChits(ctx context.Context, in *Chit, opts ...grpc.CallOption) (*Chits, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Chits)
	err := c.cc.Invoke(ctx, ChitChat_SendChits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chitChatClient) JoinChit(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*Join, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Join)
	err := c.cc.Invoke(ctx, ChitChat_JoinChit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chitChatClient) LeaveChit(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Leave, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Leave)
	err := c.cc.Invoke(ctx, ChitChat_LeaveChit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChitChatServer is the server API for ChitChat service.
// All implementations must embed UnimplementedChitChatServer
// for forward compatibility.
type ChitChatServer interface {
	GetChits(*Empty, grpc.ServerStreamingServer[Chits]) error
	SendChits(context.Context, *Chit) (*Chits, error)
	JoinChit(context.Context, *JoinRequest) (*Join, error)
	LeaveChit(context.Context, *Empty) (*Leave, error)
	mustEmbedUnimplementedChitChatServer()
}

// UnimplementedChitChatServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChitChatServer struct{}

func (UnimplementedChitChatServer) GetChits(*Empty, grpc.ServerStreamingServer[Chits]) error {
	return status.Errorf(codes.Unimplemented, "method GetChits not implemented")
}
func (UnimplementedChitChatServer) SendChits(context.Context, *Chit) (*Chits, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendChits not implemented")
}
func (UnimplementedChitChatServer) JoinChit(context.Context, *JoinRequest) (*Join, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinChit not implemented")
}
func (UnimplementedChitChatServer) LeaveChit(context.Context, *Empty) (*Leave, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaveChit not implemented")
}
func (UnimplementedChitChatServer) mustEmbedUnimplementedChitChatServer() {}
func (UnimplementedChitChatServer) testEmbeddedByValue()                  {}

// UnsafeChitChatServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChitChatServer will
// result in compilation errors.
type UnsafeChitChatServer interface {
	mustEmbedUnimplementedChitChatServer()
}

func RegisterChitChatServer(s grpc.ServiceRegistrar, srv ChitChatServer) {
	// If the following call pancis, it indicates UnimplementedChitChatServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChitChat_ServiceDesc, srv)
}

func _ChitChat_GetChits_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChitChatServer).GetChits(m, &grpc.GenericServerStream[Empty, Chits]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChitChat_GetChitsServer = grpc.ServerStreamingServer[Chits]

func _ChitChat_SendChits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Chit)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChitChatServer).SendChits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChitChat_SendChits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChitChatServer).SendChits(ctx, req.(*Chit))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChitChat_JoinChit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChitChatServer).JoinChit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChitChat_JoinChit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChitChatServer).JoinChit(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChitChat_LeaveChit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChitChatServer).LeaveChit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChitChat_LeaveChit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChitChatServer).LeaveChit(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// ChitChat_ServiceDesc is the grpc.ServiceDesc for ChitChat service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChitChat_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ChitChat",
	HandlerType: (*ChitChatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendChits",
			Handler:    _ChitChat_SendChits_Handler,
		},
		{
			MethodName: "JoinChit",
			Handler:    _ChitChat_JoinChit_Handler,
		},
		{
			MethodName: "leaveChit",
			Handler:    _ChitChat_LeaveChit_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetChits",
			Handler:       _ChitChat_GetChits_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto.proto",
}
