// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chit          string                 `protobuf:"bytes,1,opt,name=chit,proto3" json:"chit,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	TimeFormated  string                 `protobuf:"bytes,3,opt,name=timeFormated,proto3" json:"timeFormated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chit) Reset() {
	*x = Chit{}
	mi := &file_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chit) ProtoMessage() {}

func (x *Chit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chit.ProtoReflect.Descriptor instead.
func (*Chit) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{0}
}

func (x *Chit) GetChit() string {
	if x != nil {
		return x.Chit
	}
	return ""
}

func (x *Chit) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Chit) GetTimeFormated() string {
	if x != nil {
		return x.TimeFormated
	}
	return ""
}

type Chits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chit          []string               `protobuf:"bytes,1,rep,name=chit,proto3" json:"chit,omitempty"`
	Author        []string               `protobuf:"bytes,2,rep,name=author,proto3" json:"author,omitempty"`
	TimeFormated  []string               `protobuf:"bytes,3,rep,name=timeFormated,proto3" json:"timeFormated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chits) Reset() {
	*x = Chits{}
	mi := &file_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chits) ProtoMessage() {}

func (x *Chits) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chits.ProtoReflect.Descriptor instead.
func (*Chits) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{1}
}

func (x *Chits) GetChit() []string {
	if x != nil {
		return x.Chit
	}
	return nil
}

func (x *Chits) GetAuthor() []string {
	if x != nil {
		return x.Author
	}
	return nil
}

func (x *Chits) GetTimeFormated() []string {
	if x != nil {
		return x.TimeFormated
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{2}
}

type Join struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        string                 `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Time          string                 `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Join) Reset() {
	*x = Join{}
	mi := &file_proto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Join) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Join) ProtoMessage() {}

func (x *Join) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Join.ProtoReflect.Descriptor instead.
func (*Join) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{3}
}

func (x *Join) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Join) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

type Leave struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Author        string                 `protobuf:"bytes,1,opt,name=author,proto3" json:"author,omitempty"`
	Time          string                 `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Leave) Reset() {
	*x = Leave{}
	mi := &file_proto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Leave) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leave) ProtoMessage() {}

func (x *Leave) ProtoReflect() protoreflect.Message {
	mi := &file_proto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leave.ProtoReflect.Descriptor instead.
func (*Leave) Descriptor() ([]byte, []int) {
	return file_proto_proto_rawDescGZIP(), []int{4}
}

func (x *Leave) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Leave) GetTime() string {
	if x != nil {
		return x.Time
	}
	return ""
}

var File_proto_proto protoreflect.FileDescriptor

const file_proto_proto_rawDesc = "" +
	"\n" +
	"\vproto.proto\"V\n" +
	"\x04Chit\x12\x12\n" +
	"\x04chit\x18\x01 \x01(\tR\x04chit\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\"\n" +
	"\ftimeFormated\x18\x03 \x01(\tR\ftimeFormated\"W\n" +
	"\x05Chits\x12\x12\n" +
	"\x04chit\x18\x01 \x03(\tR\x04chit\x12\x16\n" +
	"\x06author\x18\x02 \x03(\tR\x06author\x12\"\n" +
	"\ftimeFormated\x18\x03 \x03(\tR\ftimeFormated\"\a\n" +
	"\x05Empty\"2\n" +
	"\x04join\x12\x16\n" +
	"\x06author\x18\x01 \x01(\tR\x06author\x12\x12\n" +
	"\x04time\x18\x02 \x01(\tR\x04time\"3\n" +
	"\x05leave\x12\x16\n" +
	"\x06author\x18\x01 \x01(\tR\x06author\x12\x12\n" +
	"\x04time\x18\x02 \x01(\tR\x04time2\x82\x01\n" +
	"\bChitChat\x12\x1c\n" +
	"\bGetChits\x12\x06.Empty\x1a\x06.Chits\"\x00\x12\x1c\n" +
	"\tSendChits\x12\x05.Chit\x1a\x06.Chits\"\x00\x12\x1b\n" +
	"\bJoinChit\x12\x06.Empty\x1a\x05.join\"\x00\x12\x1d\n" +
	"\tleaveChit\x12\x06.Empty\x1a\x06.leave\"\x00B\x16Z\x14Chit-Chat/gRPC/protob\x06proto3"

var (
	file_proto_proto_rawDescOnce sync.Once
	file_proto_proto_rawDescData []byte
)

func file_proto_proto_rawDescGZIP() []byte {
	file_proto_proto_rawDescOnce.Do(func() {
		file_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)))
	})
	return file_proto_proto_rawDescData
}

var file_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_proto_goTypes = []any{
	(*Chit)(nil),  // 0: Chit
	(*Chits)(nil), // 1: Chits
	(*Empty)(nil), // 2: Empty
	(*Join)(nil),  // 3: join
	(*Leave)(nil), // 4: leave
}
var file_proto_proto_depIdxs = []int32{
	2, // 0: ChitChat.GetChits:input_type -> Empty
	0, // 1: ChitChat.SendChits:input_type -> Chit
	2, // 2: ChitChat.JoinChit:input_type -> Empty
	2, // 3: ChitChat.leaveChit:input_type -> Empty
	1, // 4: ChitChat.GetChits:output_type -> Chits
	1, // 5: ChitChat.SendChits:output_type -> Chits
	3, // 6: ChitChat.JoinChit:output_type -> join
	4, // 7: ChitChat.leaveChit:output_type -> leave
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_proto_init() }
func file_proto_proto_init() {
	if File_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_proto_rawDesc), len(file_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_proto_goTypes,
		DependencyIndexes: file_proto_proto_depIdxs,
		MessageInfos:      file_proto_proto_msgTypes,
	}.Build()
	File_proto_proto = out.File
	file_proto_proto_goTypes = nil
	file_proto_proto_depIdxs = nil
}
